// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// JobsColumns holds the columns for the "jobs" table.
	JobsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "status", Type: field.TypeString, Default: "ongoing"},
		{Name: "created_at", Type: field.TypeTime},
	}
	// JobsTable holds the schema information for the "jobs" table.
	JobsTable = &schema.Table{
		Name:        "jobs",
		Columns:     JobsColumns,
		PrimaryKey:  []*schema.Column{JobsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// VisitsColumns holds the columns for the "visits" table.
	VisitsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "store_id", Type: field.TypeString},
		{Name: "visit_time", Type: field.TypeTime},
		{Name: "error", Type: field.TypeString, Nullable: true},
		{Name: "perimeter", Type: field.TypeInt, Nullable: true},
		{Name: "image_ur_ls", Type: field.TypeJSON},
		{Name: "job_visits", Type: field.TypeInt, Nullable: true},
	}
	// VisitsTable holds the schema information for the "visits" table.
	VisitsTable = &schema.Table{
		Name:       "visits",
		Columns:    VisitsColumns,
		PrimaryKey: []*schema.Column{VisitsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "visits_jobs_visits",
				Columns:    []*schema.Column{VisitsColumns[6]},
				RefColumns: []*schema.Column{JobsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		JobsTable,
		VisitsTable,
	}
)

func init() {
	VisitsTable.ForeignKeys[0].RefTable = JobsTable
}
